<script>
    import SvelteTable from "svelte-table";
    import {sveltify} from "../functions/utils.mjs";
    let name = "NHL Insights";
    const sampleStandingsData = [
        {
            rank: 1,
            teamName: "Boston",
            GP: 16,
            OfficialW: 14,
            RL: 2,
            OTL: 0,
            PTS: 28,
            "P%": ".875",
            RW: 11,
            ROW: 13,
            GF: 65,
            GoalsAgainst: 35,
            Diff: "+30",
            HOME: "9-0-0",
            AWAY: "5-2-0",
            "S/O": "1-0",
            Last10: "9-1-0",
            Streak: "W4",
        },
        {
            rank: 2,
            teamName: "Vegas",
            GP: 16,
            OfficialW: 13,
            RL: 3,
            OTL: 0,
            PTS: 26,
            "P%": ".813",
            RW: 10,
            ROW: 13,
            GF: 59,
            GoalsAgainst: 37,
            Diff: "+22",
            HOME: "5-2-0",
            AWAY: "8-1-0",
            "S/O": "0-0",
            Last10: "9-1-0",
            Streak: "L1",
        },
        {
            rank: 3,
            teamName: "New Jersey",
            GP: 15,
            OfficialW: 12,
            RL: 3,
            OTL: 0,
            PTS: 24,
            "P%": ".800",
            RW: 10,
            ROW: 12,
            GF: 55,
            GoalsAgainst: 38,
            Diff: "+17",
            HOME: "7-2-0",
            AWAY: "5-1-0",
            "S/O": "0-0",
            Last10: "9-1-0",
            Streak: "W9",
        },
        {
            rank: 4,
            teamName: "Los Angeles",
            GP: 17,
            OfficialW: 10,
            RL: 6,
            OTL: 1,
            PTS: 21,
            "P%": ".618",
            RW: 7,
            ROW: 9,
            GF: 56,
            GoalsAgainst: 57,
            Diff: "-1",
            HOME: "6-3-0",
            AWAY: "4-3-1",
            "S/O": "1-0",
            Last10: "7-2-1",
            Streak: "W4",
        },
        {
            rank: 5,
            teamName: "NY Islanders",
            GP: 16,
            OfficialW: 10,
            RL: 6,
            OTL: 0,
            PTS: 20,
            "P%": ".625",
            RW: 8,
            ROW: 10,
            GF: 53,
            GoalsAgainst: 41,
            Diff: "+12",
            HOME: "6-3-0",
            AWAY: "4-3-0",
            "S/O": "0-0",
            Last10: "8-2-0",
            Streak: "W1",
        },
        {
            rank: 6,
            teamName: "Winnipeg",
            GP: 14,
            OfficialW: 9,
            RL: 4,
            OTL: 1,
            PTS: 19,
            "P%": ".679",
            RW: 5,
            ROW: 9,
            GF: 43,
            GoalsAgainst: 33,
            Diff: "+10",
            HOME: "5-1-0",
            AWAY: "4-3-1",
            "S/O": "0-0",
            Last10: "7-2-1",
            Streak: "W1",
        },
        {
            rank: 7,
            teamName: "Dallas",
            GP: 15,
            OfficialW: 9,
            RL: 5,
            OTL: 1,
            PTS: 19,
            "P%": ".633",
            RW: 9,
            ROW: 9,
            GF: 56,
            GoalsAgainst: 38,
            Diff: "+18",
            HOME: "4-2-0",
            AWAY: "5-3-1",
            "S/O": "0-0",
            Last10: "5-5-0",
            Streak: "W1",
        },
        {
            rank: 8,
            teamName: "Carolina",
            GP: 15,
            OfficialW: 9,
            RL: 5,
            OTL: 1,
            PTS: 19,
            "P%": ".633",
            RW: 6,
            ROW: 7,
            GF: 47,
            GoalsAgainst: 43,
            Diff: "+4",
            HOME: "4-2-0",
            AWAY: "5-3-1",
            "S/O": "2-0",
            Last10: "6-4-0",
            Streak: "L1",
        },
        {
            rank: 9,
            teamName: "Seattle",
            GP: 16,
            OfficialW: 8,
            RL: 5,
            OTL: 3,
            PTS: 19,
            "P%": ".594",
            RW: 8,
            ROW: 8,
            GF: 52,
            GoalsAgainst: 45,
            Diff: "+7",
            HOME: "3-4-2",
            AWAY: "5-1-1",
            "S/O": "0-0",
            Last10: "6-3-1",
            Streak: "OT1",
        },
        {
            rank: 10,
            teamName: "Toronto",
            GP: 16,
            OfficialW: 8,
            RL: 5,
            OTL: 3,
            PTS: 19,
            "P%": ".594",
            RW: 7,
            ROW: 8,
            GF: 45,
            GoalsAgainst: 44,
            Diff: "+1",
            HOME: "6-2-1",
            AWAY: "2-3-2",
            "S/O": "0-0",
            Last10: "4-3-3",
            Streak: "W1",
        },
        {
            rank: 11,
            teamName: "NY Rangers",
            GP: 17,
            OfficialW: 8,
            RL: 6,
            OTL: 3,
            PTS: 19,
            "P%": ".559",
            RW: 7,
            ROW: 8,
            GF: 52,
            GoalsAgainst: 48,
            Diff: "+4",
            HOME: "4-3-3",
            AWAY: "4-3-0",
            "S/O": "0-1",
            Last10: "5-4-1",
            Streak: "W1",
        },
        {
            rank: 12,
            teamName: "Edmonton",
            GP: 16,
            OfficialW: 9,
            RL: 7,
            OTL: 0,
            PTS: 18,
            "P%": ".563",
            RW: 9,
            ROW: 9,
            GF: 59,
            GoalsAgainst: 58,
            Diff: "+1",
            HOME: "4-5-0",
            AWAY: "5-2-0",
            "S/O": "0-0",
            Last10: "6-4-0",
            Streak: "W1",
        },
        {
            rank: 13,
            teamName: "Colorado",
            GP: 13,
            OfficialW: 8,
            RL: 4,
            OTL: 1,
            PTS: 17,
            "P%": ".654",
            RW: 7,
            ROW: 7,
            GF: 49,
            GoalsAgainst: 35,
            Diff: "+14",
            HOME: "4-1-1",
            AWAY: "4-3-0",
            "S/O": "1-0",
            Last10: "6-3-1",
            Streak: "W4",
        },
        {
            rank: 14,
            teamName: "Tampa Bay",
            GP: 15,
            OfficialW: 8,
            RL: 6,
            OTL: 1,
            PTS: 17,
            "P%": ".567",
            RW: 7,
            ROW: 8,
            GF: 49,
            GoalsAgainst: 49,
            Diff: "0",
            HOME: "4-2-1",
            AWAY: "4-4-0",
            "S/O": "0-1",
            Last10: "6-3-1",
            Streak: "W1",
        },
        {
            rank: 15,
            teamName: "Florida",
            GP: 15,
            OfficialW: 8,
            RL: 6,
            OTL: 1,
            PTS: 17,
            "P%": ".567",
            RW: 7,
            ROW: 7,
            GF: 48,
            GoalsAgainst: 46,
            Diff: "+2",
            HOME: "4-1-1",
            AWAY: "4-5-0",
            "S/O": "1-0",
            Last10: "5-5-0",
            Streak: "L1",
        },
        {
            rank: 16,
            teamName: "Detroit",
            GP: 15,
            OfficialW: 7,
            RL: 5,
            OTL: 3,
            PTS: 17,
            "P%": ".567",
            RW: 6,
            ROW: 7,
            GF: 44,
            GoalsAgainst: 50,
            Diff: "-6",
            HOME: "5-2-2",
            AWAY: "2-3-1",
            "S/O": "0-1",
            Last10: "4-5-1",
            Streak: "L2",
        },
        {
            rank: 17,
            teamName: "Montréal",
            GP: 15,
            OfficialW: 8,
            RL: 6,
            OTL: 1,
            PTS: 17,
            "P%": ".567",
            RW: 5,
            ROW: 7,
            GF: 47,
            GoalsAgainst: 48,
            Diff: "-1",
            HOME: "5-3-0",
            AWAY: "3-3-1",
            "S/O": "1-0",
            Last10: "5-4-1",
            Streak: "W3",
        },
        {
            rank: 18,
            teamName: "Philadelphia",
            GP: 15,
            OfficialW: 7,
            RL: 6,
            OTL: 2,
            PTS: 16,
            "P%": ".533",
            RW: 7,
            ROW: 7,
            GF: 37,
            GoalsAgainst: 43,
            Diff: "-6",
            HOME: "4-3-1",
            AWAY: "3-3-1",
            "S/O": "0-0",
            Last10: "3-5-2",
            Streak: "L3",
        },
        {
            rank: 19,
            teamName: "Minnesota",
            GP: 15,
            OfficialW: 7,
            RL: 6,
            OTL: 2,
            PTS: 16,
            "P%": ".533",
            RW: 5,
            ROW: 6,
            GF: 42,
            GoalsAgainst: 45,
            Diff: "-3",
            HOME: "2-4-1",
            AWAY: "5-2-1",
            "S/O": "1-1",
            Last10: "6-3-1",
            Streak: "OT1",
        },
        {
            rank: 20,
            teamName: "Washington",
            GP: 17,
            OfficialW: 7,
            RL: 8,
            OTL: 2,
            PTS: 16,
            "P%": ".471",
            RW: 7,
            ROW: 7,
            GF: 49,
            GoalsAgainst: 53,
            Diff: "-4",
            HOME: "5-3-1",
            AWAY: "2-5-1",
            "S/O": "0-1",
            Last10: "3-5-2",
            Streak: "L1",
        },
        {
            rank: 21,
            teamName: "Chicago",
            GP: 14,
            OfficialW: 6,
            RL: 5,
            OTL: 3,
            PTS: 15,
            "P%": ".536",
            RW: 4,
            ROW: 6,
            GF: 38,
            GoalsAgainst: 43,
            Diff: "-5",
            HOME: "4-2-1",
            AWAY: "2-3-2",
            "S/O": "0-1",
            Last10: "4-3-3",
            Streak: "W1",
        },
        {
            rank: 22,
            teamName: "Pittsburgh",
            GP: 15,
            OfficialW: 6,
            RL: 6,
            OTL: 3,
            PTS: 15,
            "P%": ".500",
            RW: 6,
            ROW: 6,
            GF: 54,
            GoalsAgainst: 52,
            Diff: "+2",
            HOME: "3-1-1",
            AWAY: "3-5-2",
            "S/O": "0-0",
            Last10: "2-6-2",
            Streak: "OT1",
        },
        {
            rank: 23,
            teamName: "Calgary",
            GP: 14,
            OfficialW: 6,
            RL: 6,
            OTL: 2,
            PTS: 14,
            "P%": ".500",
            RW: 5,
            ROW: 6,
            GF: 41,
            GoalsAgainst: 45,
            Diff: "-4",
            HOME: "5-4-1",
            AWAY: "1-2-1",
            "S/O": "0-0",
            Last10: "3-5-2",
            Streak: "W1",
        },
        {
            rank: 24,
            teamName: "Buffalo",
            GP: 15,
            OfficialW: 7,
            RL: 8,
            OTL: 0,
            PTS: 14,
            "P%": ".467",
            RW: 6,
            ROW: 7,
            GF: 55,
            GoalsAgainst: 52,
            Diff: "+3",
            HOME: "4-5-0",
            AWAY: "3-3-0",
            "S/O": "0-0",
            Last10: "3-7-0",
            Streak: "L5",
        },
        {
            rank: 25,
            teamName: "Arizona",
            GP: 15,
            OfficialW: 6,
            RL: 8,
            OTL: 1,
            PTS: 13,
            "P%": ".433",
            RW: 6,
            ROW: 6,
            GF: 40,
            GoalsAgainst: 54,
            Diff: "-14",
            HOME: "1-2-1",
            AWAY: "5-6-0",
            "S/O": "0-0",
            Last10: "5-4-1",
            Streak: "L2",
        },
        {
            rank: 26,
            teamName: "Nashville",
            GP: 15,
            OfficialW: 6,
            RL: 8,
            OTL: 1,
            PTS: 13,
            "P%": ".433",
            RW: 5,
            ROW: 5,
            GF: 40,
            GoalsAgainst: 51,
            Diff: "-11",
            HOME: "3-3-1",
            AWAY: "3-5-0",
            "S/O": "1-1",
            Last10: "4-6-0",
            Streak: "W1",
        },
        {
            rank: 27,
            teamName: "San Jose",
            GP: 17,
            OfficialW: 5,
            RL: 9,
            OTL: 3,
            PTS: 13,
            "P%": ".382",
            RW: 2,
            ROW: 4,
            GF: 47,
            GoalsAgainst: 60,
            Diff: "-13",
            HOME: "1-5-3",
            AWAY: "4-4-0",
            "S/O": "1-3",
            Last10: "4-3-3",
            Streak: "W2",
        },
        {
            rank: 28,
            teamName: "Ottawa",
            GP: 14,
            OfficialW: 5,
            RL: 8,
            OTL: 1,
            PTS: 11,
            "P%": ".393",
            RW: 5,
            ROW: 5,
            GF: 49,
            GoalsAgainst: 0,
            Diff: "0",
            HOME: "4-4-0",
            AWAY: "1-4-1",
            "S/O": "0-0",
            Last10: "3-6-1",
            Streak: "W1",
        },
        {
            rank: 29,
            teamName: "Vancouver",
            GP: 16,
            OfficialW: 4,
            RL: 9,
            OTL: 3,
            PTS: 11,
            "P%": ".344",
            RW: 4,
            ROW: 4,
            GF: 53,
            GoalsAgainst: 66,
            Diff: "-13",
            HOME: "2-3-1",
            AWAY: "2-6-2",
            "S/O": "0-1",
            Last10: "4-5-1",
            Streak: "L3",
        },
        {
            rank: 30,
            teamName: "St Louis",
            GP: 13,
            OfficialW: 5,
            RL: 8,
            OTL: 0,
            PTS: 10,
            "P%": ".385",
            RW: 4,
            ROW: 5,
            GF: 31,
            GoalsAgainst: 48,
            Diff: "-17",
            HOME: "2-4-0",
            AWAY: "3-4-0",
            "S/O": "0-0",
            Last10: "2-8-0",
            Streak: "W2",
        },
        {
            rank: 31,
            teamName: "Columbus",
            GP: 14,
            OfficialW: 4,
            RL: 9,
            OTL: 1,
            PTS: 9,
            "P%": ".321",
            RW: 3,
            ROW: 4,
            GF: 38,
            GoalsAgainst: 61,
            Diff: "-23",
            HOME: "3-5-0",
            AWAY: "1-4-1",
            "S/O": "0-0",
            Last10: "3-6-1",
            Streak: "OT1",
        },
        {
            rank: 32,
            teamName: "Anaheim",
            GP: 15,
            OfficialW: 4,
            RL: 10,
            OTL: 1,
            PTS: 9,
            "P%": ".300",
            RW: 0,
            ROW: 2,
            GF: 42,
            GoalsAgainst: 68,
            Diff: "-26",
            HOME: "2-4-0",
            AWAY: "2-6-1",
            "S/O": "2-1",
            Last10: "3-7-0",
            Streak: "L3",
        },
    ];
    const data = sampleStandingsData;
    const columns = Object.keys(sampleStandingsData[0]);
    console.log(columns);
    console.log(sveltify(data));


    let sortBy = "rank";
    let sortOrder = 1;
</script>

<h1>Welcome to {name}!</h1>
<h1>Welcome to {columns}!</h1>

<link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css"
    integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I"
    crossorigin="anonymous"
/>

<div class="row">
    <SvelteTable
        {columns}
        rows={sveltify(data)}
        bind:sortBy
        bind:sortOrder
        classNameTable={["table table-striped"]}
        classNameThead={["table-primary"]}
        classNameSelect={["custom-select"]}
    />
</div>
