name: front-end CI

on: 
  push:
    branches:
      - main
      - dev
      - staging
      - testing
      - CI_CD
      - feature/**
      
    paths:
      - app/**
      - backend/**
      - server/**
      - .github/**
  pull_request:
    branches: 
      - main
      - dev
      - staging
      - testing

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build web
